### ISSUE TITLE
id filter usage

### ISSUE THREAD

**Issue by jayr33n** [Dashlane/dashlane-cli#102]
You should provide usage examples with the `id` filter.
In my case i have two AWS accounts with 2FA enabled and I need a way to tell them apart:
1. amazon.com - example-1@mail.com
2. amazon.com - example-2@mail.com

I was expecting that the command `dcli otp id=example-1@mail.com` outputs the first otp code but it fails.
Is there any way to achieve this?

**Comment by BenjaminOddou** [comment]
I think `id` filter already exists: 

```
dcli p id=xxxxxx
# will return any entry for which the id matches xxxxxx
```

As email is not mandatory, maybe it could be better to filter by ID directly

**Comment by jboillot** [comment]
Hello,
You should consider the result of the command `dcli p --output json amazon.com` to determine which field you would want to match.
I hope it helps!

**Comment by Mikescops** [comment]
Closing this as a solution was provided.
