### ISSUE TITLE
--other tag not working

### ISSUE THREAD

**Issue by BenjaminOddou** [Dashlane/dashlane-cli#132]
**Describe the bug**
Nothing happens when doing `dcli devices remove --other`

See docs [here](https://github.com/Dashlane/dashlane-cli/blob/master/documentation/pages/personal/devices.mdx).

**To Reproduce**
1. `dcli devices remove --other`
2. Press ⏎

**Expected behavior**
Same behavior has `dcli devices remove --all`

**Environment (please complete the following information):**
 - OS: MacOS Ventura
 - CLI Version 1.9.0

**Comment by Mikescops** [comment]
Good catch, I'm fixing this quickly.
