### ISSUE TITLE
logout vs remove current device behavior

### ISSUE THREAD

**Issue by BenjaminOddou** [Dashlane/dashlane-cli#133]
**Describe the bug**
Maybe it is intendend but I don't understand why the `logout` command does not remove the device from the current account like it does with `dcli devices remove <current-id-device>`

**To Reproduce**
1. `dcli devices remove <current-id-device>`
2. Press ⏎ on 'Yes'

The device is removed.

1. `dcli logout`
2. Press ⏎ on 'Yes'

The device is kept in the `dcli devices list`.

**Expected behavior**
Same behavior has `dcli devices remove <current-id-device>`.

**Environment (please complete the following information):**
 - OS: MacOS Ventura
 - CLI Version 1.9.0

**Comment by Mikescops** [comment]
That's very valid, I spotted this too and forgot to fill a bug, thx!
