### ISSUE TITLE
Retrieve otp from dcli read

### ISSUE THREAD

**Issue by BenjaminOddou** [Dashlane/dashlane-cli#161]
`dcli read dl://<id>/otp` returns 

```shell
error: No matching field found for "otp" in "<id>"
```

when I was expecting the same behavior as `dcli read dl://<id>/password`. In the returned response it could be nice to have the expire time like in the `dcli otp id=<id>`.

**Comment by Mikescops** [comment]
For now the read command is stupid and simple, it's just reading the content without doing any operations on it. If you look at the full json of your secret you will see the key containing the otpSecret that is the seed of the otp.
