### ISSUE TITLE
CLI Error Message for B2B Customer

### ISSUE THREAD

**Issue by juliapissarro** [Dashlane/dashlane-cli#176]
**Describe the bug**
From the Admin (VP of Security): "I followed the guide on generating the credentials and they show up in the list of credentials, but when I try to show any logs it just errors with “error: could not find team credentials”
If I do list credentials it shows the credentials that I created in the previous steps (can’t send in screenshot as it shows the access key when you list the creds)."

**Expected behavior**
List credential CLI function should not throw an error 

**Screenshots**

**Additional context**
Reported via KC

**Comment by Mikescops** [comment]
Once the admin has generated the credentials with `dcli team credentials generate`, the admin should export the generated credentials in their environment.

The documentation provided is here: https://dashlane.github.io/dashlane-cli/business#generate-credentials

Note that if the admin is using PowerShell on Windows, the SET command doesn't work, this is how to export variables:
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3

`$env:DASHLANE_TEAM_SECRET='###'`

Once the environment are exported, the admin shouldn't see the error “error: could not find team credentials” anymore.
