### ISSUE TITLE
Can't login to the CLI

### ISSUE THREAD

**Issue by bruno-brant** [Dashlane/dashlane-cli#177]
**Describe the bug**
When trying to login, be it by starting a sync or by `a whoami`, I get an error with a generic message:

```json
["errors":[{"type":"server_error","code":"internal_error","message":"Internal Error"}]
```

**To Reproduce**
1. Open terminal with the cli configured.
2. Run `dcli a whoami`
4. Type username
5. Type OTP 

**Expected behavior**
The user is successfully logged in (maybe after being prompted for password) or a descriptive error is shown.

**Screenshots**
![image](https://github.com/Dashlane/dashlane-cli/assets/1890900/7e43dd82-6c72-492b-a367-aaa6abd4da3a)

**Environment (please complete the following information):**
 - OS: Win10
 - Version: 1.13.0

**Additional context**
First time using the CLI.

**Comment by Mikescops** [comment]
Hello,

Thanks for the report.

I have traced back your API request on our monitoring and you've hit our phishing protection system.

I relaxed it, so you should now be able to use the CLI.

**Comment by bruno-brant** [comment]
Thanks, @Mikescops :)
