### ISSUE TITLE
dcli password -o json displays selector instead of printing all logins

### ISSUE THREAD

**Issue by conuaunoc** [Dashlane/dashlane-cli#182]
**Describe the bug**
According to the documentation and the YouTube tutorial, selecting JSON output should print all matching logins, not display a selector.

**To Reproduce**
1.  `dcli p -o json`
2.  See selector

**Expected behavior**
A JSON dump of all logins

**Screenshots**
![image](https://github.com/Dashlane/dashlane-cli/assets/7212610/775acaa5-a35c-4ed2-a0aa-c11fa26f8e2c)

**Environment (please complete the following information):**
 - OS: macOS 12.6.8 (Intel)
 - Version: 1.13.0 (according to dcli -V, brew reports 1.14.0, another bug?)

**Additional context**
n/a

**Comment by Mikescops** [comment]
Hello,

Thanks for reporting, indeed there is a regression in the latest updates, I'm opening a PR asap.

**Comment by conuaunoc** [comment]
Perhaps instead of a hardcoded indent of 4, make it a parameter, so we can dump JSON without prettifying when it's not needed?

I propose `-n [-1...10]`, the same range as `JSON.stringify`.

**Comment by Mikescops** [comment]
Yes sure that makes sense

**Comment by Mikescops** [comment]
Included in the new version: https://github.com/Dashlane/dashlane-cli/releases/tag/v1.14.2
