### ISSUE TITLE
dcli --version and brew list dashlane-cli versions differ

### ISSUE THREAD

**Issue by conuaunoc** [Dashlane/dashlane-cli#186]
**Describe the bug**
The versions reported by `dcli --version` and `brew list dashlane-cli` are different. `brew upgrade` says latest version already installed.

**To Reproduce**
1. `dcli --version`
2. `brew list dashlane-cli`
3. see different versions

**Expected behavior**
The two versions should be same

**Screenshots**
![Screen Shot 2023-09-01 at 3 34 59 PM](https://github.com/Dashlane/dashlane-cli/assets/7212610/3af862a9-2981-4c06-86f4-cc017c94bc78)

**Environment (please complete the following information):**
 - OS: macOS 12.6.8 (Intel)
 -  Version 1.13.0 / 1.14.0

**Additional context**
`brew remove` + `brew install` also doesn't fix it.

**Comment by Mikescops** [comment]
Thanks for reporting. 

This is a known issue, a disclaimer is on the release page. This is fixed in 1.14.2.
