### ISSUE TITLE
Email validation in `dcli sync` is too restrictive.

### ISSUE THREAD

**Issue by j-at-ch** [Dashlane/dashlane-cli#196]
**Describe the bug**
Email validation in `dcli sync` seems to be too restrictive, so that legitimate emails (including my login email) are deemed invalid by the cli.

**To Reproduce**
1. In terminal command: `dcli sync`
  `$ ? Please enter your email address:`
2. Respond with: `bob@company.health`
  `>> Not a valid email address`

**Expected behavior**
For the email with a `.health` suffix to be recognised.

**Environment:**
 - OS: MacOS
 - Version: Ventura 13.5

**Comment by Mikescops** [comment]
Thanks for reporting! I'll have a look 👍

**Comment by j-at-ch** [comment]
Thanks for this @Mikescops!

**Comment by Mikescops** [comment]
Fixed in the latest update `1.15.0`.
