### ISSUE TITLE
"The user must update to continue" on most recent version (Linux)

### ISSUE THREAD

**Issue by tylerdq** [Dashlane/dashlane-cli#200]
**Describe the bug**
Program does not successfully interact with my account, throwing the following error:

```
error: Server responded an error : {"requestId":"<ID>","errors":[{"type":"business_error","code":"expired_version","message":"This version is no longer supported. The user must update to continue."}]}
```

Please note that I removed the requestId in case it is a secret but I can provide it if needed.

**To Reproduce**
1. run `dcli p`
2. Run `dcli sync`
3. See errors

**Expected behavior**
I expected the commands to retrieve a password and to sync without error.

**Environment (please complete the following information):**
 - Void Linux x86_64; Kernel 6.5.12_1
 - dashlane-cli version 1.15.0

**Additional context**
The same issue occurs whether I build with yarn or use the most recent released linux binary. This is strange because I'm running the same version (1.15.0) on another machine with Void Linux (though on kernel 6.5.13_1) and I am able to sync just fine on that machine. I have previously been able to sync on the machine that's experiencing this bug.

**Comment by Mikescops** [comment]
Hello,

Sorry for this, a new rule on the server side has blocked the CLI, thanks for reporting, we're fixing it asap.

**Comment by tylerdq** [comment]
You're welcome! I built the new version with yarn and I am able to sync and retrieve passwords again. Thanks so much.
