### ISSUE TITLE
Brew install fails if corepack is install via brew

### ISSUE THREAD

**Issue by joshmeads** [Dashlane/dashlane-cli#215]
**Describe the bug**
If corepack is installed via brew (`brew install corepack`) the install will fail with the following:

```sh
==> Installing dashlane/tap/dashlane-cli dependency: yarn
Error: Cannot install yarn because conflicting formulae are installed.
  corepack: because both install `yarn` and `yarnpkg` binaries

Please `brew unlink corepack` before continuing.

Unlinking removes a formula's symlinks from /opt/homebrew. You can
link the formula again after the install finishes. You can `--force` this
install, but the build may fail or cause obscure side effects in the
resulting software.
```

**To Reproduce**
1. `brew install corepack`
2. `brew install dashlane/tap/dashlane-cli`
3. See error

**Expected behavior**
dashlane cli installs

**Environment (please complete the following information):**
 - OS: MacOS 14.2.1

**Comment by Mikescops** [comment]
Thanks for sharing this issue, I'll work on it when I have some time/
