### ISSUE TITLE
error: no such column: userPresenceVerification

### ISSUE THREAD

**Issue by sbaldrich** [Dashlane/dashlane-cli#253]
**Describe the bug**
Can't set up user-presence verification using biometrics.

**To Reproduce**
1.  Run `dcli configure user-presence --method biometrics` as described in [the docs](https://dashlane.github.io/dashlane-cli/personal/authentication#unlock-with-biometrics).
2. Enter master password
3. `error: no such column: userPresenceVerification` is show as output.

**Expected behavior**
Being able to unlock the vault / cli using TouchID.

**Screenshots**
<img width="473" alt="image" src="https://github.com/Dashlane/dashlane-cli/assets/1130516/a80468bf-d39f-480d-b7e7-8af8019bd94c">

**Environment (please complete the following information):**
 - OS: macOS  14.4.1
 - Version: 6.2421.0

**Additional context**
None.

**Comment by sbaldrich** [comment]
Logging out and cleaning up the local db and logging in again did the trick as the [sqlite db is recreated](https://github.com/Dashlane/dashlane-cli/blob/43d1c8265b9db5fc707079c7c270b1e9cdf1b346/src/modules/database/prepare.ts#L38) then.

**Comment by Mikescops** [comment]
Hello, thanks for sharing, it was mentioned in the release note too https://github.com/Dashlane/dashlane-cli/releases/tag/v6.2415.0, sorry for inconvenience.
