### ISSUE TITLE
SQLite error when Authenticating

### ISSUE THREAD

**Issue by JonPurvis** [Dashlane/dashlane-cli#275]
**Describe the bug**
I'm running `dcli sync`, authenticating and then getting what looks like a SQLite error:

```
error: table device has 10 columns but 11 values were supplied
```

**To Reproduce**
1. Run `dcli sync`
2. Enter email address
3. Visit verification URL in Chrome (I'm using the latest version)
4. Visit email for the 6 digit code
5. Copy and paste into terminal
6. Enter master password

**Expected behavior**
I expected to be authenticated

**Environment (please complete the following information):**
 - OS: MacOS
 - Version: Sonoma 14.2.1

**Comment by Mikescops** [comment]
Hello,

Same issue as in #101 

Run: `dcli logout` this will clean your local storage, then run `dcli sync` and login again, it will recreate the storage with the correct table model.

**Comment by JonPurvis** [comment]
Excellent thanks, logout and sync worked!
