### ISSUE TITLE
jumpcloud sso login fails after closing the browser

### ISSUE THREAD

**Issue by TwiggyWan** [Dashlane/dashlane-cli#277]
Hi
**Describe the bug**
dcli does not log in through my jumpcloud sso properly.

```
$ dcli note --debug
debug: Connected to database.
? Please enter your email address: REDACTED
# browser opens, i type my creds and 2FA, then browser closes
debug: Registering the device...
error: table device has 10 columns but 11 values were supplied
```

**To Reproduce**
1. get a jumpcloud test account
2. Run 'dcli note' and go through the authentication process

**Expected behavior**
dcli is logged in correctly.

**Screenshots**

**Environment (please complete the following information):**
 - OS: debian 
 - Version: 12 bookworm (stable, no sid)

**Additional context**
Tried with Google Chrome 127.0.6533.119 as well as with Chromium 125.0.6422.60 (through a symlink, by the way why do you look for chrome in  /opt/google/chrome/chrome and not just in $PATH? you bypass completely how google-chrome installs and manages its alternative versions)

**Comment by Mikescops** [comment]
Hello,

You have the same issue than #275 and #101.

Run: `dcli logout` this will clean your local storage, then run `dcli sync` and login again, it will recreate the storage with the correct table model.
