### ISSUE TITLE
dcli init fails

### ISSUE THREAD

**Issue by yasinzaehringer-paradime** [Dashlane/dashlane-cli#283]
**Describe the bug**
During the init of the cli on my system it throws this error:
```
error: table device has 10 columns but 11 values were supplied
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh install via homebrew and run `dcli secret`
2. Enter the details which were asked

```
? Please enter your email address: <redacted>
info: Please open the following URL in your browser: https://www.dashlane.com/cli-device-registration?login=<redacted>
? Please enter the code you received by email: <redacted>
? Please enter your master password: <redacted>
error: table device has 10 columns but 11 values were supplied
```

**Expected behavior**

It should not throw a SQL error.

**Screenshots**
I attached all the important output above in redacted form.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] MacOS 14.6.1 (23G93)
 - Version [e.g. 22]: dcli version 6.2436.0

**Additional context**

**Comment by showi** [comment]
Hello,  
You should try to log out and log back in again. There are similar closed issues.

https://github.com/Dashlane/dashlane-cli/issues/101
https://github.com/Dashlane/dashlane-cli/issues/275
