### ISSUE TITLE
`dcli sync` not syncing new logins

### ISSUE THREAD

**Issue by JonPurvis** [Dashlane/dashlane-cli#285]
**Describe the bug**
New logins added in Dashlane don't seem to be syncing to my local vault. 

**To Reproduce**
1. Add a new login to Dashlane
2. Run `dcli sync`
3. The new login doesn't appear

**Expected behavior**
I'd expect new logins to be synced to my local vault when executing `dcli sync`. I get that there may be a bit of time needed for them to appear but this is ~4 hours since I added it originally. 

I've tried logging out of the CLI and logging back in, no luck. I've even tried wiping the DB folder so the whole this is recreated, also no luck. 

**Environment (please complete the following information):**
- OS: MacOS
- Version: Sonoma 14.2.1

**Comment by Mikescops** [comment]
Hello @JonPurvis 

The sync is almost instant so it's very unlikely this is a CLI issue or server issue. 
On what kind of device have you added a new item? is it online? can your [force the sync](https://support.dashlane.com/hc/en-us/articles/202624972-Sync-your-Dashlane-data) on this device?

**Comment by JonPurvis** [comment]
Hey @Mikescops 👋 

Yeah, I added the new item on the same machine I'm running the CLI, via the web app. Interestingly, when forcing a sync, I get the following error:

> Sync failed: Error: Data length should be at least 36 long but was 0

It came up with a little error symbol so I inspected the console logs and saw that. Not sure if that's in any way related to this?

**Comment by Mikescops** [comment]
Alright, I won't be able to debug this without getting more information, so we'll have to go to a regular support process.
Can you open a ticket here please: https://support.dashlane.com/ 
Once you go through the chatbot, you can request to talk to an agent and at the end the bot will give you a ticket number. Paste it here so I can follow up with your request.

**Comment by JonPurvis** [comment]
Hey @Mikescops 

Apologies for the delay in getting back to you. I got a support ticket opened and provided the information I was asked for, including a screenshot of the error I'm seeing in my browser console. 

The ticket number is: **2355694**

Thanks!
