### ISSUE TITLE
Windows release flagged as malicious by several security vendors

### ISSUE THREAD

**Issue by CPTechNet** [Dashlane/dashlane-cli#290]
The 'dcli-win-x64-signed.exe' and 'dcli-win-x64.exe' executables are flagged as malicious by several security vendors. 

VirusTotal scan details for v6.2436.0 linked below:

dcli-win-x64-signed.exe
https://www.virustotal.com/gui/file/3c319193cbce38253b50db23ff9e857cf56d25146c97a301cef45c0d8eeac6d0

dcli-win-x64.exe
https://www.virustotal.com/gui/file/c830eef6ea0bcf1d96ec13573dac1ee76653a048f6caa178313857d360be7e8e

**Comment by Mikescops** [comment]
Hello,

Thanks for checking this with us.
You can report them as false positive, we own the code and know what's inside.

Have a good rest of the day.

**Comment by Mikescops** [comment]
We'll try to reach out to AV vendors to make sure they whitelist us.
