### ISSUE TITLE
Invalid Algorithm

### ISSUE THREAD

**Issue by mzellho** [Dashlane/dashlane-cli#299]
**Describe the bug**
With the latest release 6.2247.0, I can no longer fetch OTP values - I get "error: Invalid algorithm", which does not seem to be thrown in dashlane-cli, so maybe it's about a transitive dependency? I works nicely in the previous version 6.2436.0.

**Screenshots**
![image](https://github.com/user-attachments/assets/5a3a217c-f7af-4670-a55d-c5a59e86a2b3)
![image](https://github.com/user-attachments/assets/1f964aaa-3e57-4ed3-a78f-2678e25d93ac)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 24.04.1 LTS

**Comment by Mikescops** [comment]
Hello,

Sorry for this bug I may have created this issue while solving another one for someone else.

Can you print your credential as `json` and check wether your secret for otp is contained in `otpSecret` or `otpUrl`.

If it's `otpUrl` can you send just the beginning of it `oauth://<something>` ?

Please make sure you don't paste any secret on Github!

**Comment by mzellho** [comment]
@Mikescops , thanks for the quick reply! The secrect is contained in both properties, `otsSecret` and `otpUrl` (as a query parameter of the `otpauth://totp` url)

![image](https://github.com/user-attachments/assets/ff6cf190-1c24-4270-a226-e30f78af6b09)

**Comment by Mikescops** [comment]
And the secret is the same in both?

**Comment by mzellho** [comment]
yes, same value

**Comment by Mikescops** [comment]
Can you try [v6.2447.1](https://github.com/Dashlane/dashlane-cli/releases/tag/v6.2447.1) when it will be available (in a few minutes) ?

**Comment by mzellho** [comment]
almost! unfortunately now the OTP returned is 0 (tried multiple OTPs):

![image](https://github.com/user-attachments/assets/bff5c399-c0ba-4ce9-a932-ffcbac386730)

**Comment by Mikescops** [comment]
Sorry @mzellho I wasn't woken up, I tested with all credentials I had, it should be fine in the v6.2447.2

**Comment by Mikescops** [comment]
@mzellho is it good now?

**Comment by mzellho** [comment]
@Mikescops : works perfectly, thanks a lot for the quick fixes!

**Comment by Mikescops** [comment]
You're welcome! Happy to have reports like this too 👍
