### ISSUE TITLE
Error: table device had 10 columns but 11 values were supplied

### ISSUE THREAD

**Issue by johnnyBira** [Dashlane/dashlane-cli#305]
**Describe the bug**
I just made a fresh install of this tool and no matter what command I run I get this error:
```sh
error: table device had 10 columns but 11 values were supplied
```

I tried the suggested fix in [this issue](https://github.com/Dashlane/dashlane-cli/issues/101) but it didn't help.

Every time I run a command I'm promoted to go through the 2FA main authentication  process. Is this normal?

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a fresh install of `dcli`
2. Run i.e. `dcli read dl://SOME-ID/field` (or any other command).
4. For me this produces the following error:
```sh
error: table device had 10 columns but 11 values were supplied
```

**Expected behavior**
To be able to retrieve my secrets using the cli.

**Screenshots**
![Screenshot 2024-12-30 at 19 18 02](https://github.com/user-attachments/assets/1614e2d7-1c88-45e6-98b5-36b37ce5e1a3)

**Environment (please complete the following information):**
 - MacOS
 - Version: 15.1 (24B83)

**Comment by johnnyBira** [comment]
Manually deleting the database is what helped in the end. Figured it out thanks to [this comment](https://github.com/Dashlane/dashlane-cli/issues/275#issuecomment-2278158917).

**Comment by Mikescops** [comment]
Hey, glad you found the solution, thanks for sharing!
