### ISSUE TITLE
Add a homebrew formula

### ISSUE THREAD

**Issue by tenfourty** [Dashlane/dashlane-cli#39]
Homebrew is how most Mac folks who use the command line install software. It would be great to have a homebrew formula for this tool instead of having to manually install/update.

This:

`brew install dashlane-cli`

Instead of:
```
brew install typescript
git clone git@github.com:Dashlane/dashlane-cli.git
cd dashlane-cli
npm run build
npm link
npm install
````

**Comment by trystendsmyth** [comment]
I made a tap for myself: https://github.com/trystendsmyth/dotfiles/blob/master/Formula/dashlane-cli.rb
This repo needs more notability before Brew will accept the addition to core.

**Comment by Mikescops** [comment]
Marking as stale as we could not make it to the official homebrew, for now the ruby script is available in the repository.

**Comment by Kageetai** [comment]
I am 100% sure whether this is related, but the command `brew install --build-from-source dashlane-cli.rb` in the README.md doesn't work, so do I need to use this custom script from @trystendsmyth above? I have never done this with homebrew, so how do I use this?

**Comment by Mikescops** [comment]
You must have brew installed on your machine, clone or download this repository and run the command inside the downloaded folder.

**Comment by Kageetai** [comment]
Ah okay, that makes sense, thans for the explanation

**Comment by Mikescops** [comment]
I consider this one done as we just opened a homebrew tap 🎉  >> https://github.com/Dashlane/homebrew-tap
