### ISSUE TITLE
Unable to access keychain

### ISSUE THREAD

**Issue by DaRacci** [Dashlane/dashlane-cli#43]
OS: ArchLinux x86_64
Kernel: 5.18.11-264-tkg-pds 
dashlane-cli-version: 1.0.0
libsecret-version: 0.20.5-2

tried with uploaded binary and locally made, no difference.
Other programs has no issue using the keychain.

![image](https://user-images.githubusercontent.com/90304606/181864621-ee64d2f0-131f-49b2-977e-a1ac52bff51b.png)

**Comment by jboillot** [comment]
Hello and thanks for submitting this issue!
Would it be possible for you to re-run this command with the parameter `--debug`? Thus the first error message should be printed.

**Comment by jboillot** [comment]
I just think about it now but for Linux the library we are using to reach OS keychains is the one from GNOME: libsecret.
So, I'm not sure which is the keychain you're using but if it's not this one you would have to download it (at least for now).

**Comment by DaRacci** [comment]
This is the libsecret info and deubg output

![image](https://user-images.githubusercontent.com/90304606/181865058-4f628894-a9c0-4a9d-9f91-54d199d54488.png)

**Comment by jboillot** [comment]
Thank you, the problem seems related to missing configuration of gnome-keyring.
I admit I don't know much about Arch but may you try the first comment of this thread? https://www.reddit.com/r/archlinux/comments/q5s0s5/vscode_git_keychain_error/

**Comment by jboillot** [comment]
May you try to install those extra dependencies `pacman -S gnu2 pass`?
I have to admit I don't know much about Arch and how it works with libsecret.

**Comment by DaRacci** [comment]
I've already got the dependencies install, I'll investigate some more as maybe it is on my end but im unsure.

**Comment by jboillot** [comment]
If you want to experiment more easily you might want to try running https://www.npmjs.com/package/keytar-cli that is the CLI version of the library we use to reach the OS keychain.

**Comment by jboillot** [comment]
Hello,
I got it running on an Arch VM with i3 and here are the things I've done:
- `pacman -S  libsecret pass gnome-keyring`
- In `/etc/pam.d/login` I have added `auth optional pam_gnome_keyring.so` and `session optional pam_gnome_keyring.so auto_start`
- In `/etc/pam.d/passwd` I have added `password optional pam_gnome_keyring.so`

Please tell me if it works for you :)
Jérôme

**Comment by DaRacci** [comment]
could you send a screenshot of your busctl from that session, Im not seeming to get the same thing.

**Comment by jboillot** [comment]
Here is the screenshot you requested!
![image](https://user-images.githubusercontent.com/52931370/182256379-4683c59d-f171-4933-a535-0075aab241ca.png)

**Comment by jboillot** [comment]
(I had to run it in an X client)

**Comment by DaRacci** [comment]
Yeah it seems to be an issue with ly or something, When logging in through the terminal and starting i3 manually im able to get it working but not with ly.
