### ISSUE TITLE
Cannot login via CLI - OTP2 not supported

### ISSUE THREAD

**Issue by uniflare** [Dashlane/dashlane-cli#44]
Hello,

I can login fine on the browser.
However the CLI keeps saying master password incorrect after trying to login by running `dcli-win sync`.
`The master password you provided is incorrect, would you like to retry?`

**Comment by Mikescops** [comment]
Hello @uniflare, I'll need more information : 

- operating system info
- steps to reproduce 

To further debug this, I'll need your login email, but we'll go through the official support channel to so as i don't want any private information on Github.

**Comment by uniflare** [comment]
Heya, no problem;

Operating System: Windows 11 Pro x64
STR:

1. Download dcli-win.exe
2. Open Windows Command Prompt, 'cd' to dcli-win.exe location.
3. Run Command: dcli-win.exe reset
4. Choose Yes
5. run Command dcli-win.exe sync
6. Enter your email address
7. Enter your OTP code
8. Enter your Master Password

Result:
The master password you provided is incorrect, would you like to retry?

Expected:
Sync successfully

**Comment by Mikescops** [comment]
Hello,

Can you confirm you can login on other apps with this exact email and master password?

Can you open a ticket on our user support mentioning your login email, please link this thread in the ticket and let me know the ticket number you get here.

https://support.dashlane.com/hc/en-us/requests/new

**Comment by uniflare** [comment]
Yes I can sign into Dashlane fine. Only this CLI is giving me trouble.

**Comment by Mikescops** [comment]
So I took a look at your account and you have OTP at each login, which means that your vault is encrypted with an extra secret. And we haven't added the support of it in the CLI, so we need to work on it next to unblock you.

Concerning the support ticket I'll close it.

**Comment by uniflare** [comment]
Oh I see thanks for the explanation.
Is there a roadmap or possible ball-park eta for this feature?

**Comment by Mikescops** [comment]
> Oh I see thanks for the explanation. Is there a roadmap or possible ball-park eta for this feature?

It's still a side project so we don't have clear roadmap and ETA for it, if it get enough traction the company will include it as a main app and we'll have more investment in it.

Concerning this I'll take a look when I have some free time on top of my list.

**Comment by uniflare** [comment]
I see no problem thanks.
One last question - does the API support this?
What I mean to say, is it possible to add this functionality ourselves by implementing an API response for example, or does this require API development also that is not accessible to us?

**Comment by Mikescops** [comment]
The API is ready (as it's used by the other apps), but without documentation you'll spend quite sometime figuring out how to do it.
