### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by BenjaminOddou** [Dashlane/dashlane-cli#53]
Hello,

I am trying to build something on top of the CLI to make it more easy to manipulate. I am doing auth tests but I now have the error below. How to get rid of it ?

```shell
dcli sync
? Please enter your email address: somemail@test.com
DashlaneApiError: Rate limit exceeded
    at requestApi (/snapshot/dashlane-cli-master/dist/requestApi.js:79:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async registerDevice (/snapshot/dashlane-cli-master/dist/middleware/registerDevice.js:15:30)
    at async getSecretsWithoutDB (/snapshot/dashlane-cli-master/dist/crypto/keychainManager.js:81:50)
    at async connectAndPrepare (/snapshot/dashlane-cli-master/dist/database/connectAndPrepare.js:24:21)
    at async Command.<anonymous> (/snapshot/dashlane-cli-master/dist/index.js:34:29)
    at async Command.parseAsync (/snapshot/dashlane-cli-master/node_modules/commander/lib/command.js:917:5) {
  code: 'rate_limit_exceeded',
  type: 'rate_limit_error'
}
```

Also is there a limit of calling `dcli password` / `dcli note` or `dcli otp` ? Many thanks in advance for your help

**Comment by Mikescops** [comment]
Hello,

Indeed every endpoints of the API have specific rate limits and the one you get here is most likely at device registration (it's a pretty strong one to avoid abuse). 
Unfortunately I can't provide you any bypass to this rate limit system as we currently don't have any external developer program.
So you'll have to wait a few minutes or hours (I'm out of office atm, but i can check later what is the exact limit on this endpoint) for the rate limit to unblock you. 

Concerning `dcli password` and alt, as long as the sync is not involved there are no rate limit to fetch data from your vault.

**Comment by BenjaminOddou** [comment]
Hello @Mikescops thank you very much for your response. I totally understand the point. Even though, I think it could be nice to know (even approximately) the rate limits of the API.

Another question regarding the API.  Is there a documentation regarding the response object ? For `dcli password` I built something like this:

```ts
export interface Password {
    subdomainOnly?:            string;
    url?:                      string;
    modificationDatetime?:     string;
    title?:                    string;
    creationDatetime:          string;
    email?:                    string;
    searchableText?:           string;
    status?:                   string;
    autoLogin?:                string;
    localeFormat?:             string;
    password?:                 string;
    anonID:                    string;
    checked?:                  string;
    id:                        string;
    autoProtected?:            string;
    category?:                 string;
    useFixedURL?:              string;
    linkedServices?:           string;
    numberUse?:                string;
    lastUse?:                  string;
    userModificationDatetime?: string;
    isFavorite?:               string;
    login?:                    string;
    strength?:                 string;
    lastBackupTime?:           string;
    secondaryLogin?:           string;
    sharedObject?:             string;
    temporaryAutoLogin?:       string;
    userSelectedURL?:          string;
    note?:                     string;
    syncID?:                   string;
    otpURL?:                   string;
    otpSecret?:                string;
}
```

**Comment by Mikescops** [comment]
I'll tell you the rate limit when I have a chance to grab my work laptop.

It's not an API response as it's the result of the parsing of the encrypted XML file (that is actually what we call a transaction of the vault). 
You probably missed it, but it's already typed here : https://github.com/Dashlane/dashlane-cli/blob/master/src/types.ts#L119

**Comment by BenjaminOddou** [comment]
@Mikescops Thank you for all these details ! Indeed I totally missed this file 😅

**Comment by Mikescops** [comment]
Hello,
The rate limit is at 40 calls per day for a given login!
Which on a normal usage is pretty fair as no one is registering 40 devices per day usually.

**Comment by BenjaminOddou** [comment]
Hello @Mikescops thanks for the feedback ! It's nice to know the limit. Indeed on normal usage it's more than enough 😄
