### ISSUE TITLE
Missing file extension on linux and macos released assets

### ISSUE THREAD

**Issue by welcoMattic** [Dashlane/dashlane-cli#65]
Windows asset has .exe extention, but linux and macos assets don't.
I would like to install the package on my Arch but I can't guess the format of the package for linux. Is it possible to make it more explicit?

Thanks

![image](https://user-images.githubusercontent.com/773875/222162681-fd138b37-903c-44ea-881f-1e2160c68e01.png)

**Comment by jboillot** [comment]
Hello,
I'm not sure I understand well your question, but those files all are executables. They aren't packages.

To execute it on arch you first have to grant yourself the ability to execute it using `chmod u+x dcli-linux` then execute it using `./dcli-linux`.

If you want to be able to execute it from any directory, you can move it to a directory in your path (you can print it using `echo $PATH`) and then execute the cli using `dcli-linux`.

Don't hesitate to tell me if I haven't answered your question or if you have more!

**Comment by welcoMattic** [comment]
Oh sorry, I didn't release (or even try) that they are executable. Sorry for the noise
