### ISSUE TITLE
Arm package

### ISSUE THREAD

**Issue by BenjaminOddou** [Dashlane/dashlane-cli#67]
Hello,

From this [PR](https://github.com/Dashlane/dashlane-cli/pull/59), why not putting `pkg:macos-arm` in the [pkg line](https://github.com/Dashlane/dashlane-cli/blob/4b17f53acd03a8f46f5860107516af4e269b3289/package.json#LL27C8-L27C93) of the `package.json` ? IMHO, It would be nice to have the `arm-binary` in the release too 😄.

**Comment by Mikescops** [comment]
Hello,

Because you need an arm runner to be able to build for arm architecture and so far Github Actions doesn't provide ARM runners.

**Comment by Mikescops** [comment]
Worth mentioning you can use homebrew to build the ARM version from the source easily 👍
