### ISSUE TITLE
Error: Cannot load module

### ISSUE THREAD

**Issue by uniflare** [Dashlane/dashlane-cli#79]
### Environment:
Operating System: Windows 11 Professional (10.0.22621 Build 22621)
Account Privileges: Administrator
Working Directory: C:\Apps\dcli
Dashlane-CLI Version: 1.5.0

### Repro:
1. Run the command: dcli-win_x64.exe reset
2. Choose Yes
3. Run dcli-win_x64.exe sync
4. Enter OTP
5. Enter Master Password
6. Run dcli-win_x64.exe p

### Result:
```
C:\Apps\dcli>dcli
node:internal/modules/cjs/loader:1024
  throw err;
  ^

Error: Cannot find module 'C:\Users\unifl\AppData\Roaming\npm\node_modules\@dashlane\cli\dist\index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by Mikescops** [comment]
I see in your command output `C:\Apps\dcli>dcli`, which executable is this?
It sounds like you're launching the node project (and not the release build) as per the error path `AppData\Roaming\npm\node_modules\@dashlane`.
Can you confirm?

**Comment by uniflare** [comment]
Oh strange, I swear I put in the correct exe name, this must be in my path somehow :D.
It is working after testing again. Sorry to waste your time.

I have noticed another issue though, when retrieving a password (after a multi choice option), the password is doubled in the clipboard. I will open a new ticket.

Thanks again :)
