### ISSUE TITLE
Ask mp only when needed

### ISSUE THREAD

**Issue by tidalf** [Dashlane/dashlane-cli#82]
Hello, 

I'd like to use the cli in a script to retrieve team informations using the team memberlist option. 
It currently asks for the mp (while it's not required to use only the api), it'd be nice to ask for it only when required.

thanks!

**Comment by jboillot** [comment]
Hello,

Currently, the device secret key that is required to call the endpoint you're talking of is encrypted using the local key that is stored in the keychain, or encrypted using the master password in the local storage. That is why your master password is asked.

From your message, I guess you do not want to store your master password, even encrypted. The only solution I can think of would be to add the possibility to disable the save of the encrypted master password in the local storage, but still save the local key in the keychain. Thus, you could recover the device secret key.

This would add some granularity in the secrecy options.

**Comment by Mikescops** [comment]
Cyril message is a bit simplified, his initial use case is to use the CLI on a CI (and calling methods that don't require decrypting any content).
Another solution could be to use the MP as env variable so the MP is in the CI secrets manager.
Another one could be to be able to export the device secrets so they can be stored in the CI secrets manager.
