### ISSUE TITLE
Gateway Error When Trying do first-time sync on windows 10

### ISSUE THREAD

**Issue by darburgess** [Dashlane/dashlane-cli#98]
Hello Dashlane Team,

I finally got dcli (v1.6.0) installed on my corporate machine after pointing NodeJS to my local certs (this was also causing issues with the base CLI when I tried installing the executable itself). However now I am getting a different issue!

**What I am Trying**
Per the readme, just trying to do my initial sync with `dcli sync`

**What Happens**
The CLI prompts me for my email, then after a few seconds of processing the response I get the following error:
`ERROR: Response code 504 (Gateway Timeout)`

Thanks for your help with this

**Comment by Mikescops** [comment]
Hello,

That sounds like a network issue, that could be your enterprise network blocking the request for instance.

I don't have much guidance for now, I will think about adding a better debug mode to the CLI so we can get the full HTTP answer and see who is replying this Gateway Timeout

**Comment by Mikescops** [comment]
I finally reproduced this bug! Can you confirm that you have the authenticator app setup on your account?

During the first sync we try to register your new device but we are waiting for 2FA validation, so a notification to approve is sent to your Dashlane Authenticator app.

For now the timeout and messaging to mention that you need to approve the notification is not great and we're going to improve it!

**Comment by Mikescops** [comment]
As new informative messages have been added to the 2FA process + addition of a verification method selector, I expect this error to be clearer.

If you see that your issue happen again, please reopen this thread.
